### ISSUE TITLE
Module not found: Can't resolve 'aws-appsync/lib/link/auth-link'

### ISSUE THREAD

**Issue by webdevike** [aws-samples/aws-serverless-appsync-app#9]
Npm start and npm run build fail due to this issue.

**Comment by patrickeddy** [comment]
@ikey2244 did you managed to resolve this?

**Comment by maturiaditya** [comment]
I managed to resolve it by making following modification to the App.js file

- import { AUTH_TYPE } from "aws-appsync/lib/link/auth-link"; (remove)

+ import AWSAppSyncClient, { AUTH_TYPE } from "aws-appsync"; (change)
